#if !canImport(ObjectiveC)
import XCTest

extension SwiftDictionaryPerformanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftDictionaryPerformanceTests = [
        ("testDictionary_1", testDictionary_1),
        ("testDictionary_10", testDictionary_10),
        ("testDictionary_100", testDictionary_100),
        ("testDictionary_100_000", testDictionary_100_000),
        ("testDictionary_10_000", testDictionary_10_000),
        ("testDictionary_10_000_000", testDictionary_10_000_000),
        ("testDictionary_1_000", testDictionary_1_000),
        ("testDictionary_1_000_000", testDictionary_1_000_000),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SwiftDictionaryPerformanceTests.__allTests__SwiftDictionaryPerformanceTests),
    ]
}
#endif
